# Site settings
title: bock auf tv
slogan: Irgendwer muss sich den Mist ja ansehen...

# description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bockauf.tv" # the base hostname & protocol for your site

lsi: false
timezone: Europe/Vienna
permalink: /:categories/:title

paginate: 3
paginate_path: "/p:num"

# Build settings
markdown: kramdown

gems: [jekyll-paginate]

sass:
#  style: :compressed
  style: :nested
